image: node:latest 

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

services:
  - mysql:5.7
  - docker:dind

build:
  stage: build
  script:
    - apt-get update && apt-get install -y python3-pip
    - ls
    - cd client
    - ls
    - npm install
    - npm run build 
  after_script:
    - cd ../

test:
  stage: test
  image: docker:20.10.16
  services:
    - name: registry.hub.docker.com/library/docker:20.10.16-dind
      alias: docker
  script:
    - ls
    - docker build --network=host -t myapp .
    - docker run --name mysql -e MYSQL_ROOT_PASSWORD=comsc -d mariadb:latest
    - sleep 20
    - docker exec -i mysql localhost -u root -pcomsc -e 'CREATE DATABASE app_db;'
    - docker exec -i mysql localhost -u root -pcomsc app_db < database/db_initialise.sql
    - docker run --name myapp -d -p 5000:5000 --link mysql:mysql myapp
    - cd ./flask-server
    - pip install pytest
    - pytest test_api.py

node_test:
  image: node:latest
  script:
    - ls
    - cd ../
    - apt-get update && apt-get install -y python3-pip
    - cd client
    - npm install
    - npm test
  after_script:
    - cd ../


deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y python3-pip
  # in deploy just for testing, should probably be moved 
  # put these in requirements 
  # add them to build or something 
    - pip install --upgrade pip
    - pip install -r requirements.txt
    
    
    # Doing this in the pipeline is bad, but it works  
    # - python server.py &
    # - npm start
