image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

services:
  - docker:mysql:5.7

before_script:
  - apt-get update && apt-get install -y python3-pip default-mysql-client
  - echo "Test"
  - cd ./client
  - npm install

build:
  stage: build
  script:
    - npm run build 

test:
  stage: test
  script:
  # Pass with no tests has been added because 
  # Pipeline was created before tests were properly added
    - echo "We need to add some tests lol then fix this"
    # Run Jest/React tests
    - npm test
    - service mysql start
    - mysql -u root -h localhost -e 'CREATE DATABASE app_db;'
    - mysql -u root -h localhost app_db < db_initialise.sql
    - cd ..
    - cd ./flask-server
    - python3 server.py &
    - export SERVER_PID=$!
    - pip install pytest
    - pip install requests
    - python3 test_api.py
    - service mysql stop
    - kill $SERVER_PID


deploy:
  stage: deploy
  script:
  # in deploy just for testing, should probably be moved 
  # put these in requirements 
  # add them to build or something 
    - pip install --upgrade pip
    - pip install -r requirements.txt
    
    
    # Doing this in the pipeline is bad, but it works  
    # - python server.py &
    # - npm start
