image: node:latest

stages:
  - build
  # - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - echo "Test"
  - cd ./client
  - npm install

build:
  stage: build
  script:
    - npm run build

# test:
#   stage: test
#   script:
#     - npm test    

deploy:
  stage: deploy
  script:
    - pip install --upgrade pip
    - pip install flask
    - pip install flask_session
    - pip install mysql-connector-python
    - pip install flask_bcrypt
    - npm install -g npm@9.6.2
    - npm install axios
    - npm install react-router-dom
    - npm install @mantine/core
    - npm install @tabler/icons-react
    - python server.py &
    - npm start
