image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update && apt-get install -y python3-pip
  - echo "Test"
  - cd ./client
  - npm install

build:
  stage: build
  script:
    - npm run build 

test:
  stage: test
  script:
  # Pass with no tests has been added because 
  # pipeline was created before tests were properly added
    - echo "We need to add some tests lol then fix this"
    # - npm test

deploy:
  stage: deploy
  script:
    - pip install --upgrade pip
    - pip install flask
    - pip install flask_session
    - pip install mysql-connector-python
    - pip install flask_bcrypt
    - npm install -g npm@9.6.2
    - npm install axios
    - npm install react-router-dom
    - npm install @mantine/core
    - npm install @tabler/icons-react
    # Doing this in the pipeline is bad, but it works  
    # - python server.py &
    # - npm start
