image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update && apt-get install -y python3-pip
  - echo "Test"
  - cd ./client
  - npm install

build:
  stage: build
  script:
    - npm run build 

test:
  stage: test
  script:
  # Pass with no tests has been added because 
  # pipeline was created before tests were properly added
    - echo "We need to add some tests lol then fix this"
    # - npm test
    - cd ..
    - cd ./flask-server
    - pip install pytest
    - pip install requests
    - pip install --upgrade pip
    - pip install flask
    - pip install flask_session
    - pip install mysql-connector-python
    - pip install flask_bcrypt

    - apt-get upgrade -y
    - apt-get install -y sudo
    - sudo service mysql enable 
    - sudo apt-get install -y mysql-server
    - sudo service mysql start
    - sudo service mysql status

    - MYSQL_ROOT_PASSWORD='comsc'

    - mysql -u root -p${MYSQL_ROOT_PASSWORD} < ../database/db_initialise.sql
    - python3 server.py
    - python3 test_api.py
    - FLASK_PID=$!
    - kill $FLASK_PID

deploy:
  stage: deploy
  script:
  # in deploy just for testing, should probably be moved 
  # put these in requirements 
  # add them to build or something 
    - pip install --upgrade pip
    - pip install flask
    - pip install flask_session
    - pip install mysql-connector-python
    - pip install flask_bcrypt
    
    
    # Doing this in the pipeline is bad, but it works  
    # - python server.py &
    # - npm start
