image: node:latest 

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

variables:
  DOCKER_HOST: tcp://0.0.0.0:2375

build:
  stage: build
  script:
    - apt-get update && apt-get install -y python3-pip
    - ls
    - cd client
    - ls
    - npm install
    - npm run build 
  after_script:
    - cd ../

unit_test:
  stage: test
  image: python:3.9
  services:
    - name: mysql:latest
      env:
        MYSQL_ROOT_PASSWORD: ""
        MYSQL_HOST: mysql
        MYSQL_USER: runner
        MYSQL_PASSWORD: comsc
        MYSQL_DATABASE: app_db
  before_script:
    - apt-get update
    - apt-get install -y default-mysql-server default-mysql-client libmysqlclient-dev
    - MYSQL_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql)
    - echo "MySQL container IP address: $MYSQL_IP"
    - mysql -hmysql -uroot -p'' -e "CREATE DATABASE app_db;"
    - cat /database/initialise_db.sql | mysql -hmysql -uroot -p'' app_db
  script:
    - cd flask-session
    - pip install pytest
    - pytest

    
node_test:
  stage: test
  image: node:latest
  script:
    - ls
    - apt-get update && apt-get install -y python3-pip
    - cd client
    - npm install
    - npm test
  after_script:
    - cd ../



deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y python3-pip
  # in deploy just for testing, should probably be moved 
  # put these in requirements 
  # add them to build or something 
    - pip install --upgrade pip
    - pip install -r requirements.txt
    
    
    # Doing this in the pipeline is bad, but it works  
    # - python server.py &
    # - npm start
