version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: comsc
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    command: mysqld --innodb-flush-method=O_DIRECT --innodb-use-native-aio=0

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_URL: mysql+pymysql://root:comsc@db:3306/app_db

  pytest:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:comsc@db:3306/app_db
    entrypoint: pytest